version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-go-bookstore
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go-bookstore:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: go-bookstore
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: